import "./globals.css";

import MobileLayout from "./mobileLayout";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// breakpoint에 따라 return을 다르게 함
export default function RootLayout({ children }) {
  return <MobileLayout props={children} />;
}
